build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64

    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3

    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # create new conda environment
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy cython"
  - activate test-environment
  # ????
  - echo CALL "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64> C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat
  # build package
  - python setup.py build_ext --inplace

test_script:
  - python test.py
